export const create = 'todomvc.create'
export const remove = 'todomvc.remove'
export const toggle = 'todomvc.toggle'
export const save = 'todomvc.save'
export const toggleAll = 'todomvc.toggleAll'
export const clearCompleted = 'todomvc.clearCompleted'
